name: .NET Core

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build, test and create nuget packages
      run: dotnet test --configuration Release
    - name: Publish to feed
      run: dotnet push **/*.nupkg
           --api-key ${{ secrets.NUGET_KEY }}
           --source https://api.nuget.org/v3/index.json
